[package]
name = "list-zipper"
version = "0.1.0"
edition = "2024"
license = "GPL-3.0-or-later"
description = "a zipper data structure for sequenceable data types"

[dependencies]
itertools = { version = "0.14" }
